version: "3.7"

services:
  db:
    image: postgres:13.0
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: depot
    ports:
      - "5433:5432"
  web:
    container_name: depot
    build:
      context: .
      dockerfile: Dockerfile
    image: depot
    ports:
      - "5199:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresDatabase=User ID=postgres;Password=root;Server=db;Port=5432;Database=depot;Include Error Detail=true;
      - JwtOptions__Issuer=http://localhost:7199
      - JwtOptions__Audience=http://localhost:7199
      - JwtOptions__SecretKey=this is my custom Secret key for authentication dont use in production lol
volumes:
  db_data: